// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpficfxcouwrmypkacli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwZmljZnhjb3V3cm15cGthY2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0OTg1MjksImV4cCI6MjA4NzA3NDUyOX0.a-2jfauncL2H-WtVQ9ibG_4EQllv0XL8uON9ogukfEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});